### ISSUE TITLE
error cros

### ISSUE THREAD

**Issue by mrbardia72** [sadhakbj/Laravel-Vue-Graphql#1]
Access to fetch at 'http://localhost/graphql' from origin 'http://127.0.0.1:8000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by sadhakbj** [comment]
You can use chrome extension for this or install laravel cors package to allow it.

**Comment by mrbardia72** [comment]
chrome extension؟
